// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIdG8QnVhcazvblfOyfWuuY_JwgJXVsg',
    appId: '1:1023685173404:android:cc7262ccf1b3aa54888d59',
    messagingSenderId: '1023685173404',
    projectId: 'nikah-time-332406',
    storageBucket: 'nikah-time-332406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWYdC8tW8ZlBn_DiVrkaFPzXUmwP8oJ8',
    appId: '1:1023685173404:ios:9e75904efd592bea888d59',
    messagingSenderId: '1023685173404',
    projectId: 'nikah-time-332406',
    storageBucket: 'nikah-time-332406.firebasestorage.app',
    androidClientId: '1023685173404-1fv28orkif7lf5p7jerqlalha0v43qus.apps.googleusercontent.com',
    iosClientId: '1023685173404-go99snh3am30qgjgd8up1kld3mbr7ra8.apps.googleusercontent.com',
    iosBundleId: 'ru.nikahtime',
  );

}