/// Flutter icons MenuIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcons
///      fonts:
///       - asset: fonts/MenuIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuIcons {
  MenuIcons._();

  static const _kFontFam = 'MenuIcons';
  static const String? _kFontPkg = null;

  static const IconData arcticles = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
